---
- name: Ensure has an entry in /etc/hosts which assigns an IPv4 address.
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: '^{{ proxmox_eth0_ipv4 | default(ansible_default_ipv4.address)}}'
    line: "{{ proxmox_eth0_ipv4 | default(ansible_default_ipv4.address) }} {{ proxmox_fqdn | default('') }} {{ ansible_hostname }} pvelocalhost"

- name: Ensure hostname is not on the same line of localhost
  lineinfile:
    state: absent
    dest: /etc/hosts
    regexp: '^127(.*){{ ansible_hostname }}'
    backup: true

- name: Ensure hostname is not on an ipv6 line
  lineinfile:
    state: present
    dest: /etc/hosts
    backrefs: true
    regexp: '(.*::.*){{ ansible_hostname }}(.*)'
    line: '\1\2'
    backup: true

- name: setup IPV4 forwarding for NAT
  lineinfile:
    state: present
    dest: "/etc/sysctl.conf"
    regexp: '^#?net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
  tags:
    - nat

- name: Upload network configuration file
  template:
    src:  "{{ proxmox_interfaces_template }}"
    dest: "{{ proxmox_interfaces_file }}.ansible"
  register: network_template_result
  when: proxmox_interfaces_template | length

- name: Configure network interfaces (need reboot if changes)
  command: cp -f {{ proxmox_interfaces_file }}.ansible {{ proxmox_interfaces_file }}
  register: network_result
  changed_when: true
  when: proxmox_interfaces_template | changed
