---


- name: run sysupgrade
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 600

- name: remove unused os-prober
  apt:
    pkg: os-prober
    state: absent

- name: install usefull packages for Proxmox VE
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-pip

- name: install proxmoxer and requests
  pip:
    name: "{{ item }}"
  with_items:
    - requests
    - proxmoxer
